### ISSUE TITLE
errors when strating  Multiple Ip Dictonary Attack

### ISSUE THREAD

**Issue by emdaitaj** [R4stl1n/SSH-Brute-Forcer#12]
root@my-server /ssh/SSH-Brute-Forcer/src python SSH* -I 23a -d True -p 22 -C c6
[*] Simple SSH Brute Forcer: By r4stl1n
[*] Loaded 23704 Targets
[*] Loaded 9070 Usernames
[*] Loaded 9070 Passwords
[*] Brute Force Starting
Traceback (most recent call last):
  File "SSHBruteForce.py", line 280, in <module>
    sshBruteForce.startUp()
  File "SSHBruteForce.py", line 84, in startUp
    self.multipleTargets(options)
  File "SSHBruteForce.py", line 142, in multipleTargets
    self.dictionaryAttackMultiple()
  File "SSHBruteForce.py", line 194, in dictionaryAttackMultiple
    int(target[1]), self.timeoutTime)
ValueError: invalid literal for int() with base 10: '2.48.2.44\r'

**Comment by emdaitaj** [comment]
Ture was misktake in here and the erroe doesn't change when correct that too

**Comment by ghost** [comment]
This is due the fact that 'find' function is being used which will return -1 upon error.
https://docs.python.org/2/library/string.html#string.find

**Comment by r4stl1n** [comment]
^
