### ISSUE TITLE
Missing Paramiko Dependency.

### ISSUE THREAD

**Issue by najibman** [R4stl1n/SSH-Brute-Forcer#13]
The Solution 👍 
pip install paramiko
or
pip3 install paramiko

**Comment by Cenzor** [comment]
i installed 'pip install paramiko' and 'pip3 install paramiko', but it don't work:
"Missing Paramiko Dependency." Why?

**Comment by nelodvn** [comment]
Hi @Cenzor,

The installation of paramiko was successful? Are you using virtual env?

**Comment by Cenzor** [comment]
Hi @nelodvn,
Yes, installation was success. I don't use virtual env

**Comment by r4stl1n** [comment]
Generally when using python packages you do the following:

pip install -r requirements.txt

To install all the dependencies.
