### ISSUE TITLE
Single username?

### ISSUE THREAD

**Issue by franx47** [R4stl1n/SSH-Brute-Forcer#3]
Hi, 

Thanks for the script. Works great and fast! 

But, how if I want to make a test by attacking with only single username, eg: root. And with random password specified by the length of the string. 

Perhaps something like this: 
python SSHBruteForce.py -i [target_IP] -p 22 -t 15 -T 30 -d True -u root -a 10 -l 8 -v

Thanks.

**Comment by r4stl1n** [comment]
just have the single username in the file.
