### ISSUE TITLE
Add combo list

### ISSUE THREAD

**Issue by Demontager** [R4stl1n/SSH-Brute-Forcer#4]
Could you please implement bruteforcing by combo list. E.g. combo list as follows:
admin:admin
root:password
root:123456789
same like hydra does. From man hydra:
"
       -C FILE
              colon separated "login:pass" format, instead of -L/-P options

"

**Comment by sami1979** [comment]
In the util.py there is already a method fileContentsToTuple(fileName). Seems like R4stl1n had the idea already when creating the class. 
@R4stl1n Could you make a comment if already planned to implement this and in which way you like to do it?
If I find some freetime I will take a look to this in deep.

**Comment by sami1979** [comment]
commited a new branch with a solution.
@R4stl1n  can you review this one, please?

**Comment by Demontager** [comment]
@sami1979 I tested commited changes, it accepts -C flag, but continues testing against single username, not like offered in combo.

$ python SSHBruteForce.py -v -i 192.168.1.1 -d True -p 22 -C ./combo.txt -t 15
[_] Simple SSH Brute Forcer: By r4stl1n 
[_] Brute Forcing 192.168.1.1 
[_] Loaded 9 Usernames 
[_] Loaded 9 Passwords 
[_] Brute Force Starting 
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: admin
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: admin
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: password
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: ubnt
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: ubnt
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: pfsense
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: user
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: ubntftw
[_] Adding Target: 192.168.1.1, Testing with username: admin, testing with password: 
[_] Adding Target: 192.168.1.1, Testing with username: root, testing with password: admin
[_] Adding Target: 192.168.1.1, Testing with username: root, testing with password: admin
[_] Adding Target: 192.168.1.1, Testing with username: root, testing with password: password
[_] Adding Target: 192.168.1.1, Testing with username: root, testing with password: ubnt
[*] Adding Target: 192.168.1.1, Testing with username: root, testing with password: ubnt

combo.txt:
admin:admin
root:admin
root:password
root:ubnt
admin:ubnt
root:pfsense
user:user
ubnt:ubntftw

**Comment by r4stl1n** [comment]
I apologize for not accepting and looking at the patches sooner i don't receive notifications like i should so have to manually check repos. _Mostly because im lazy to update the email_
