### ISSUE TITLE
Start info is printed before bruteforce when running in brute force mode

### ISSUE THREAD

**Issue by nelodvn** [R4stl1n/SSH-Brute-Forcer#6]
When the -d True flag is present, the showStartInfo() is called:
$ python SSHBruteForce.py -i 192.168.0.117 -U /tmp/users -P /tmp/pass -d True 
[_] Simple SSH Brute Forcer: By r4stl1n 
[_] Brute Forcing 192.168.0.117 
[_] Loaded 6 Usernames 
[_] Loaded 111 Passwords 
[*] Brute Force Starting 

When -d is False (bruteforce mode), the showStartInfo() is called after brute force started, the message is not printed until brute force is done:

$ python SSHBruteForce.py -i 192.168.0.117 -U /tmp/users -P /tmp/pass
(no msg here)

**Comment by nelodvn** [comment]
Fixed in pull request #8

**Comment by r4stl1n** [comment]
Thanks for the fix.
