### ISSUE TITLE
Program freezes randomly

### ISSUE THREAD

**Issue by DarrenRainey** [R4stl1n/SSH-Brute-Forcer#9]
I've tried using this program on a large file of devices to test but it also freezes randomly not sure if this is because of machines going offline and online or auth rejects any help would be great

**Comment by LucasRoot** [comment]
It's happening with me too, I think it's because the machine goes offline, but when it goes online the program doesn't continue

**Comment by r4stl1n** [comment]
It looks like it freezes as the app is waiting for a response from the machine. However there is a chance it can get stuck... essentially make sure the machine is still online and mark where the script ended. However to be fair.. medusa and hydra are probably better to use now a days.
